services:
  spring-boot-backend:
    build: .
    container_name: spring-boot-backend
    mem_limit: 512m
    networks:
      - beancart-net
    ports:
      - "8000:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/beancartdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_REDIS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - maven-cache:/workspace/app/.m2  # Mount volume for Maven dependencies

  db:
    image: postgres:15-alpine
    container_name: beancart-db
    networks:
      - beancart-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: beancartdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: beancart-redis
    networks:
      - beancart-net
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  beancart-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  maven-cache:  # Define the volume for Maven cache
